version: '3'
services:
  source:
    build: 
      context: ../../
      dockerfile: apps/docker/recipes/source.Dockerfile
      args: 
        ENTRY_PATH: .
        INIT_SCRIPT: apps/docker/scripts/source.sh
    restart: always
    volumes:  
      - ../../:/app
      - nodemodules:/app/node_modules
      
  storybook: 
    build: 
      context: ../../
      dockerfile: apps/docker/recipes/run.Dockerfile
      args: 
        ENTRY_PATH: apps/storybook
        INIT_SCRIPT: apps/docker/scripts/run.sh
    volumes:
      - ../../:/app
      - nodemodules:/app/node_modules
    depends_on:
      - source
    ports:
      - 8000:8000

volumes:
    nodemodules: